name: gabix
services:
  mongo:
    restart: always
    container_name: mongo-db
    image: mongo:7.0.1
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-log:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-scripts:/var/scripts/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "gabixadmin"
      MONGO_INITDB_ROOT_PASSWORD: "gabixadmin"
      MONGO_INITDB_ROOT_DATABASE: "gabix"
    ports:
      - "27017:27017"

  api:
    restart: always
    build: ../api
    container_name: api
    ports:
      - "4000:4000"
    environment:
      ENVIRONMENT: "local"
      MONGO_PROTOCOL: "mongodb"
      MONGO_HOST: "mongo:27017"
      MONGO_DB: "gabix"
      MONGO_USER: "api"
      MONGO_PWD: "api"
      API_PORT: 4000
    volumes:
      - type: bind
        source: ../api
        target: /api
    depends_on:
      - mongo

  angular:
    container_name: angular
    build: ../angular
    volumes:
      - type: bind
        source: ../angular
        target: /usr/src/app
    ports:
      - 4200:5000
